### PR TITLE
updated/moved event model

### PR DESCRIPTION
**Pull request by Enshaedn**
Updated event model for API Gateway

### CODE REVIEW

**Comment by Enshaedn** [comment]
Change log: 
* Added default value for event_id
* Added default value for created_timestamp
* Removed default value for activity_type

event_id and created_timestamp are both set within the Lambda function and are therefore unnecessary to pass through API Gateway as a parameter. Default values will be transformed in Lambda before posting to DynamoDB.

**Comment by MrSamsa42** [comment]
These changes make sense to me.  I reviewed the template and confirmed that the changes were made.

**Review by MrSamsa42 — APPROVED** [review]
I agree with the rationale for updating the model.  I confirmed that the changes are as described in the PR.

**Review by T-travis — APPROVED** [review]
It looks good to me.  Is there a reason we switched from camel case?  I can't remember why but Toddy wanted event_id instead of eventID.  Is this a DynamDB rule or design thing?  Also, kinda separate but somewhat related is the db schema.  Are we going with no sort key or will this not affect the event_model.js?

**Comment by Enshaedn** [comment]
I don't think we had ever used camel case for the parameters. The swagger model, I believe, was always set as event_id. Parts of the swagger do still say eventID, but those are just names/placeholders for the parameter event_id. Perhaps that should be changed, but that was how it is demo'd in the PetStore swagger I believe and also how I did it last quarter. 

To my knowledge it is not a Dynamo thing but a design thing. As for sort keys in Dynamo I'm not sure if we are or aren't, but it won't affect the model either way.

**Pull request merged**
