### PR TITLE
Jon feature/events filter

### PR DESCRIPTION
**Pull request by MrSamsa42**
This is a first attempt at a filtering endpoint.

### CODE REVIEW

**Review by Enshaedn — APPROVED** [review]
I think it looks good and appreciate the comments. I was able to follow along with the logic of the function. In my opinion there should be enhanced/additional logging for CloudWatch - created issue #46.

Tested:
image
image
image

Query parameters work and the error catch for invalid parameters works too.

**Comment by T-travis** [comment]
I tested all the endpoints in the demo, and they all work well search parameters.  However, they all need to handle error responses correctly.  Problems:

- If I use this https://api-jona.2edusite.com/v1/events/eventsFilter?contact_name=Jo, note "Jo" is not a person in the db, then I get a 200 response and this output in the browser {"Items":[],"Count":0,"ScannedCount":4}.  I believe in this example it should be a 404 response and maybe a message for that in the browser.

- If I use this https://api-jona.2edusite.com/v1/events/eventsFilter?contact_name, note this is a bad request from the client, I get a 200 response and this message in the browser {"errorMessage":"ExpressionAttributeValues contains invalid value: One or more parameter values were invalid: An AttributeValue may not contain an empty string for key :contact_name","errorType":"ValidationException","stackTrace":["Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)","Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)","Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)","Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)","Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)","AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)","/var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10","Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)","Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)","Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)"]}.  Here we should get a 400 response and maybe some message in the browser that is helpful.

Please update all endpoints to have the appropriate HTTP status codes.

Bug created [here](https://github.com/ActoKids/api/issues/50)

**Review by T-travis — APPROVED** [review]
Approving PR but see this[ issue/bug](https://github.com/ActoKids/api/issues/50) for future API-Team work and changes.

**Comment by MrSamsa42** [comment]
Adding these endpoints here, for anyone who wants to do additional testing:
This filters on contact_name, returning all events where contact_name = "Jonathan"
https://api-jona.2edusite.com/v1/events/eventsFilter?contact_name=Jonathan
This filters on contact_name AND contact_email
https://api-jona.2edusite.com/v1/events/eventsFilter?contact_name=Jonathan&contact_email=jradler@gmail.com
This filters on contact_name AND contact_email AND approver
https://api-jona.2edusite.com/v1/events/eventsFilter?contact_name=Jonathan&contact_email=jradler@gmail.com&approver=Zeus
This returns an error message, because contactName is not a valid parameter
https://api-jona.2edusite.com/v1/events/eventsFilter?contactName=Jonathan

**Comment by MrSamsa42** [comment]
I made some changes to Lambda (not yet committed).  API gateway now returns a 400 response if the user enters an invalid search parameter OR an empty string.   I'm researching the correct response for an empty array of results from the db.

**Pull request merged**
