### PR TITLE
Travis for dev env

### PR DESCRIPTION
**Pull request by Stakada**
Fixed .travis.yml indentation problem

### CODE REVIEW

**Comment by dashinay** [comment]
Based on the changes, tests and travis report I approve the pr.

**Review by dashinay — APPROVED** [review]
Based on the changes, tests and travis report I approve the pr.

**Comment by bmenaz** [comment]
Checked the status of travis ci checks and yaml configuration, all seems to be correct and passing. Now just needs to be tested if it gets pushed into dev will it be deploying just to make sure.

**Review by bmenaz — APPROVED** [review]
Checked the status of travis ci checks and yaml configuration, all seems to be correct and passing. Now just needs to be tested if it gets pushed into dev will it be deploying just to make sure.

**Pull request merged**
